# Generated by Django 6.0.6 on 2026-07-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userdetail_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
