# Generated by Django 6.0.6 on 2026-07-05 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userdetail_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('user_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to='api.userdetail')),
            ],
        ),
    ]
