# Generated by Django 6.0.6 on 2026-07-05 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_companydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='user_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='api.userdetail'),
        ),
        migrations.AddConstraint(
            model_name='companydetail',
            constraint=models.UniqueConstraint(fields=('user_detail',), name='unique_company_detail_per_user'),
        ),
    ]
